create table salary
(
    id                         int auto_increment
        primary key,
    companyCode                varchar(256) null comment '',
    companyName                varchar(256) null comment '',
    staffName                  varchar(256) null comment '',
    idNumber                   varchar(256) null comment '',
    basePay                    varchar(256) null comment '',
    position                   varchar(256) null comment '',
    payLevel                   varchar(256) null comment '',
    levelPay                   varchar(256) null comment '',
    remarkA                    varchar(256) null comment '',
    remarkB                    varchar(256) null comment '',
    subsidyTag                 varchar(256) null comment '',
    workSubsidy                varchar(256) null comment '',
    liveSubsidy                varchar(256) null comment '',
    workAdjustSubsidy          varchar(256) null comment '',
    governmentSubsidy          varchar(256) null comment '',
    phoneSubsidy               varchar(256) null comment '',
    nannySubsidy               varchar(256) null comment '',
    onlyChildSubsidy           varchar(256) null comment '',
    babySubsidy                varchar(256) null comment '',
    visitsSubsidy              varchar(256) null comment '',
    minorityNationalitySubsidy varchar(256) null comment '',
    remarkC                    varchar(256) null comment '',
    remarkD                    varchar(256) null comment '',
    remarkE                    varchar(256) null comment '',
    totalGrossPay              varchar(256) null comment '',
    subsidyPay                 varchar(256) null comment '',
    totalDeductions            varchar(256) null comment '',
    housingProvidentFund       varchar(256) null comment '',
    individualIncomeTax        varchar(256) null comment '',
    pensionInsurance           varchar(256) null comment '',
    annuity                    varchar(256) null comment '职业年金个人缴费',
    adjustedPay                varchar(256) null comment '补扣工资',
    totalNetPay                varchar(256) null comment '实发合计'
);

